In [3]:
import numpy as np

In [4]:
data = np.loadtxt(r"C:\Users\Admin\OneDrive\Desktop\balaji\Python\fit.txt",dtype=str)

In [5]:
data[0:5,:]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [6]:
data.shape

(96, 6)

In [7]:
date = data[:,0]
step_count = data[:,1]
mood = data[:,2]
calories_burned = data[:,3]
hours_of_sleep = data[:,4]
active = data[:,5]

In [8]:
step_count = np.array(step_count,dtype=int)
calories_burned = np.array(calories_burned,dtype=int)
hours_of_sleep = np.array(hours_of_sleep,dtype=int)


In [9]:
step_count.mean().round()

2936.0

In [10]:
np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([40, 27, 29], dtype=int64))

In [11]:
np.unique(active,return_counts=True)

(array(['Active', 'Inactive'], dtype='<U10'), array([42, 54], dtype=int64))

In [12]:
'''
1. on which day the step count was highest and the calories burned ?
hypothesis: more steps count,more calories
'''

'\n1. on which day the step count was highest and the calories burned ?\nhypothesis: more steps count,more calories\n'

In [13]:
np.max(step_count)

7422

In [14]:
np.argmax(step_count)

69

In [15]:
date[np.argmax(step_count)]

'14-12-2017'

In [16]:
calories_burned[np.argmax(step_count)]  

243

In [17]:
np.argmin(step_count)

2

In [18]:
calories_burned[np.argmin(step_count)]  

0

In [19]:
np.mean(calories_burned)

93.44791666666667

In [20]:
np.mean(step_count)


2935.9375

In [21]:
''' 
hypothesis: more steps count,better mood
'''

' \nhypothesis: more steps count,better mood\n'

In [32]:
np.mean(step_count[mood == 'Sad']).round()



2103.0

In [31]:
step_count[mood == 'Happy'].mean().round()

3393.0

In [30]:
step_count[mood == 'Neutral'].mean().round()

3154.0

In [ ]:
# what is my usual mood when step count > 4000 : how many times

np.unique(mood[step_count > 4000], return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([22,  9,  7], dtype=int64))

In [29]:
np.unique(mood[step_count < 2000], return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([13,  8, 18], dtype=int64))