In [1]:
#numpy: numerical python 

import numpy as np


In [2]:
list = [1,2,3,4]

for i in list:
    print(i**2)

1
4
9
16


In [3]:
[i**2 for i in list]

[1, 4, 9, 16]

In [4]:
arr = np.array([1,2,3,4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
arr**2

array([ 1,  4,  9, 16])

In [8]:
list1 = [i for i in range (1,101)]

In [9]:
arr1 = np.array(list1)

In [10]:
%timeit [i**2 for i in list1]

15.5 μs ± 1.42 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [11]:
%timeit arr1**2

1.48 μs ± 605 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
arr4 = np.arange(12)

In [13]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.sum(arr4)

66

In [15]:
np.min(arr4)

np.max(arr4)

11

In [16]:
np.mean(arr4)

5.5

In [17]:
arr4.ndim

1

In [18]:
len(arr4) #len function only  use in 1d array 

12

In [19]:
arr4.size #size function use multi dimational  array

12

In [20]:
np.array([True,False])

array([ True, False])

In [21]:
np.array([True,False,5])

array([1, 0, 5])

In [22]:
np.array([True,False,5,5.0])

array([1., 0., 5., 5.])

In [23]:
np.array([True,False,5,5.0,"string"])

array(['True', 'False', '5', '5.0', 'string'], dtype='<U32')

In [24]:
np.ones(12,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
np.zeros(12,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
arr5 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

arr5    #2d array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
type(arr5)

numpy.ndarray

In [28]:
arr5.ndim

2

In [29]:
arr5.size

9

In [30]:
arr5.shape

(3, 3)

In [31]:
arr6 = np.arange(50,150,10)

arr6

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [32]:
arr6[4]

90

In [33]:
arr6[2:5:2]

array([70, 90])

In [34]:
arr6[-2:-5:-2]

array([130, 110])

In [35]:
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr5[0,1]

2

In [37]:
arr5[0,1:3]

array([2, 3])

In [38]:
arr5[1,0:2]

array([4, 5])

In [39]:
arr5[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [40]:
arr6

arr6[[0,1,3]]

array([50, 60, 80])

In [41]:
list

[1, 2, 3, 4]

In [42]:
list[0],list[1],list[3]

(1, 2, 4)

In [44]:
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(arr5,axis=0) #vertical calculation 

array([12, 15, 18])

In [ ]:
np.sum(arr5,axis=1) #horizantel calculation 

array([ 6, 15, 24])

In [50]:
np.min(arr5,axis=0)

array([1, 2, 3])

In [51]:
np.max(arr5,axis=0)

array([7, 8, 9])

In [54]:
np.mean(arr5,axis=0,dtype=int)

array([4, 5, 6])

In [53]:
np.average(arr5,axis=0)

array([4., 5., 6.])

In [55]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
#Mask 
arr4 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [57]:
mask = (arr4 % 2 == 0)

In [58]:
arr4[mask]

array([ 0,  2,  4,  6,  8, 10])

In [59]:
arr4[arr4 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [62]:
arr4[arr4 > 6]

array([ 7,  8,  9, 10, 11])

In [67]:
arr4[(arr4 % 2==0) | (arr4 % 3==0)]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [68]:
arr4[(arr4 % 2==0) & (arr4 % 3==0)]

array([0, 6])

In [69]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
np.where(arr4 % 2==0,'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd'], dtype='<U4')

In [71]:
arr11 = np.array([-3,4,27,34,-2,0,-45,-11,4,0])

In [73]:
np.where(arr11>0,1,-1)

array([-1,  1,  1,  1, -1, -1, -1, -1,  1, -1])

In [74]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [75]:
np.all(arr4==0)

False

In [76]:
np.any(arr4==0)

True